---
name: cmpsc-100-spring-2019-lab2
break: true
indent: 4
---
src/main:
    java:
        labtwo/DisplayGraphicalScene.java:
            --single 10 --language Java
            --multi 3 --language Java
            --fragment "String" --count 1
            --fragment "int" --count 3
            --fragment "new Date(" --count 1
            --fragment "Scanner" --count 1
            --fragment "next" --count 4
            --fragment "Color" --count 5
            --fragment "setFill(" --count 5
            --fragment "new Rectangle" --count 3
            --fragment "new Ellipse" --count 2
            --fragment "setTitle(" --count 1
            --fragment "setScene(" --count 1
            --fragment "show(" --count 1

writing/reflection.md:
    --paragraphs 2 --exact
    --words 150
--commits 7
